theme: jekyll-theme-midnight
show_downloads: false
title: Unofficial Figura FAQ
description: Lists frequently asked questions about Figura.
github:
  repository_url: https://github.com/Slymeball/figura-faq/wiki
